function createLifecycleDef({
  type,
  label,
  category,
  accepts = [],
  produces = [],
  inputs = [],
  outputs = [],
  defaultConfig = {},
  uiSchema = {},
}) {
  return {
    type,
    kind: 'lifecycle',
    category,
    label,
    color: '#ffe066',
    accepts,
    produces,
    inputs,
    outputs,
    defaultConfig,
    uiSchema,
    metadata: { stage: category },
  };
}

const DATA_INPUTS = ['image', 'tabular', 'text'];

export const LIFECYCLE_NODES = [
  createLifecycleDef({
    type: 'lifecycle.split',
    label: 'Split',
    category: 'data-control',
    accepts: DATA_INPUTS,
    produces: DATA_INPUTS,
    inputs: [{ name: 'dataset', datatype: 'tensor', shape: [], optional: false }],
    outputs: [
      { name: 'train', datatype: 'tensor', shape: [] },
      { name: 'val', datatype: 'tensor', shape: [] },
      { name: 'test', datatype: 'tensor', shape: [] },
    ],
    defaultConfig: {
      split_type: 'train_val_test',
      train_pct: 70,
      val_pct: 20,
      test_pct: 10,
      shuffle: true,
      seed: 42,
      stratify_by: 'label',
      folds: 5,
    },
    uiSchema: {
      split_type: { type: 'enum', options: ['train_val_test', 'kfold', 'stratified', 'time_series'], label: 'Split Type' },
      train_pct: { type: 'number', min: 1, max: 98, step: 1, label: 'Train %' },
      val_pct: { type: 'number', min: 0, max: 98, step: 1, label: 'Val %' },
      test_pct: { type: 'number', min: 0, max: 98, step: 1, label: 'Test %' },
      shuffle: { type: 'boolean', label: 'Shuffle' },
      seed: { type: 'number', min: 0, max: 999999, step: 1, label: 'Seed' },
      stratify_by: { type: 'string', label: 'Stratify By' },
      folds: { type: 'number', min: 2, max: 20, step: 1, label: 'K-Folds' },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.dataloader',
    label: 'DataLoader',
    category: 'data-control',
    accepts: DATA_INPUTS,
    produces: ['dataloader'],
    inputs: [{ name: 'dataset', datatype: 'tensor', shape: [], optional: false }],
    outputs: [{ name: 'loader', datatype: 'dataloader', shape: [] }],
    defaultConfig: {
      batch_size: 32,
      shuffle: true,
      num_workers: 4,
      pin_memory: true,
      drop_last: false,
      prefetch_factor: 2,
      persistent_workers: true,
      device_transfer: 'auto',
    },
    uiSchema: {
      batch_size: { type: 'number', min: 1, max: 4096, step: 1 },
      shuffle: { type: 'boolean' },
      num_workers: { type: 'number', min: 0, max: 64, step: 1 },
      pin_memory: { type: 'boolean' },
      drop_last: { type: 'boolean' },
      prefetch_factor: { type: 'number', min: 1, max: 16, step: 1 },
      persistent_workers: { type: 'boolean' },
      device_transfer: { type: 'enum', options: ['cpu', 'gpu', 'auto'] },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.model',
    label: 'Model Definition',
    category: 'modeling',
    accepts: ['dataloader', ...DATA_INPUTS],
    produces: ['model'],
    inputs: [{ name: 'loader', datatype: 'dataloader', shape: [], optional: true }],
    outputs: [{ name: 'model', datatype: 'model', shape: [] }],
    defaultConfig: {
      family: 'resnet50',
      pretrained: true,
      num_classes: 10,
      freeze_backbone: false,
    },
    uiSchema: {
      family: {
        type: 'enum',
        options: ['resnet18', 'resnet50', 'efficientnet', 'vit', 'xgboost', 'random_forest', 'mlp', 'bert', 'roberta', 'lstm', 'custom'],
        label: 'Model',
      },
      pretrained: { type: 'boolean', label: 'Pretrained' },
      num_classes: { type: 'number', min: 1, max: 100000, step: 1, label: 'Num Classes' },
      freeze_backbone: { type: 'boolean', label: 'Freeze Backbone' },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.loss',
    label: 'Loss Function',
    category: 'training-config',
    accepts: ['model'],
    produces: ['loss'],
    inputs: [{ name: 'model', datatype: 'model', shape: [], optional: true }],
    outputs: [{ name: 'loss', datatype: 'loss', shape: [] }],
    defaultConfig: {
      name: 'cross_entropy',
      reduction: 'mean',
      class_weights: 'auto',
      label_smoothing: 0.1,
    },
    uiSchema: {
      name: { type: 'enum', options: ['cross_entropy', 'focal_loss', 'dice_loss', 'mse', 'huber', 'triplet_loss', 'contrastive_loss', 'custom'] },
      reduction: { type: 'enum', options: ['mean', 'sum', 'none'] },
      class_weights: { type: 'string', label: 'Class Weights' },
      label_smoothing: { type: 'number', min: 0, max: 1, step: 0.01 },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.training',
    label: 'Training',
    category: 'training-execution',
    accepts: ['model', 'loss', 'dataloader', ...DATA_INPUTS],
    produces: ['trained_model', 'metrics', 'logs'],
    inputs: [
      { name: 'model', datatype: 'model', shape: [], optional: false },
      { name: 'loader', datatype: 'dataloader', shape: [], optional: false },
      { name: 'loss', datatype: 'loss', shape: [], optional: true },
      { name: 'config', datatype: 'dict', shape: [], optional: true },
    ],
    outputs: [
      { name: 'trained_model', datatype: 'model', shape: [] },
      { name: 'metrics', datatype: 'dict', shape: [] },
      { name: 'logs', datatype: 'dict', shape: [] },
      { name: 'checkpoints', datatype: 'dict', shape: [] },
    ],
    defaultConfig: {
      optimizer: 'adamw',
      learning_rate: 0.001,
      weight_decay: 0.0001,
      scheduler: 'cosine',
      epochs: 50,
      gradient_clipping: 1,
      mixed_precision: true,
      checkpoint_frequency: 1,
      early_stopping: true,
      monitor_metric: 'val_loss',
      gradient_accumulation: 1,
      logging_backend: 'tensorboard',
    },
    uiSchema: {
      optimizer: { type: 'enum', options: ['adam', 'sgd', 'adamw'] },
      learning_rate: { type: 'number', min: 0, max: 10, step: 0.0001 },
      weight_decay: { type: 'number', min: 0, max: 1, step: 0.0001 },
      scheduler: { type: 'enum', options: ['cosine', 'step', 'linear', 'none'] },
      epochs: { type: 'number', min: 1, max: 10000, step: 1 },
      gradient_clipping: { type: 'number', min: 0, max: 100, step: 0.1 },
      mixed_precision: { type: 'boolean' },
      checkpoint_frequency: { type: 'number', min: 1, max: 1000, step: 1 },
      early_stopping: { type: 'boolean' },
      monitor_metric: { type: 'string' },
      gradient_accumulation: { type: 'number', min: 1, max: 512, step: 1 },
      logging_backend: { type: 'enum', options: ['tensorboard', 'mlflow', 'wandb', 'none'] },
    },
  }),
];
