function createLifecycleDef({
  type,
  label,
  category,
  accepts = [],
  produces = [],
  inputs = [],
  outputs = [],
  defaultConfig = {},
  uiSchema = {},
}) {
  return {
    type,
    kind: 'lifecycle',
    category,
    label,
    color: '#ffe066',
    accepts,
    produces,
    inputs,
    outputs,
    defaultConfig,
    uiSchema,
    metadata: { stage: category },
  };
}

const DATA_INPUTS = ['image', 'tabular', 'text'];
const MODEL_INPUTS = ['model', 'trained_model'];
const PREDICTION_INPUTS = ['predictions', ...DATA_INPUTS];

export const LIFECYCLE_NODES = [
  createLifecycleDef({
    type: 'lifecycle.split',
    label: 'Split',
    category: 'data-control',
    accepts: DATA_INPUTS,
    produces: DATA_INPUTS,
    inputs: [{ name: 'dataset', datatype: 'tensor', shape: [], optional: false }],
    outputs: [
      { name: 'train', datatype: 'tensor', shape: [] },
      { name: 'val', datatype: 'tensor', shape: [] },
      { name: 'test', datatype: 'tensor', shape: [] },
    ],
    defaultConfig: {
      split_type: 'train_val_test',
      train_pct: 70,
      val_pct: 20,
      test_pct: 10,
      shuffle: true,
      seed: 42,
      stratify_by: 'label',
      folds: 5,
    },
    uiSchema: {
      split_type: { type: 'enum', options: ['train_val_test', 'kfold', 'stratified', 'time_series'], label: 'Split Type' },
      train_pct: { type: 'number', min: 1, max: 98, step: 1, label: 'Train %' },
      val_pct: { type: 'number', min: 0, max: 98, step: 1, label: 'Val %' },
      test_pct: { type: 'number', min: 0, max: 98, step: 1, label: 'Test %' },
      shuffle: { type: 'boolean', label: 'Shuffle' },
      seed: { type: 'number', min: 0, max: 999999, step: 1, label: 'Seed' },
      stratify_by: { type: 'string', label: 'Stratify By' },
      folds: { type: 'number', min: 2, max: 20, step: 1, label: 'K-Folds' },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.dataloader',
    label: 'DataLoader',
    category: 'data-control',
    accepts: DATA_INPUTS,
    produces: ['dataloader'],
    inputs: [{ name: 'dataset', datatype: 'tensor', shape: [], optional: false }],
    outputs: [{ name: 'loader', datatype: 'dataloader', shape: [] }],
    defaultConfig: {
      batch_size: 32,
      shuffle: true,
      num_workers: 4,
      pin_memory: true,
      drop_last: false,
      prefetch_factor: 2,
      persistent_workers: true,
      device_transfer: 'auto',
    },
    uiSchema: {
      batch_size: { type: 'number', min: 1, max: 4096, step: 1 },
      shuffle: { type: 'boolean' },
      num_workers: { type: 'number', min: 0, max: 64, step: 1 },
      pin_memory: { type: 'boolean' },
      drop_last: { type: 'boolean' },
      prefetch_factor: { type: 'number', min: 1, max: 16, step: 1 },
      persistent_workers: { type: 'boolean' },
      device_transfer: { type: 'enum', options: ['cpu', 'gpu', 'auto'] },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.model',
    label: 'Model Definition',
    category: 'modeling',
    accepts: ['dataloader', ...DATA_INPUTS],
    produces: ['model'],
    inputs: [{ name: 'loader', datatype: 'dataloader', shape: [], optional: true }],
    outputs: [{ name: 'model', datatype: 'model', shape: [] }],
    defaultConfig: {
      family: 'resnet50',
      pretrained: true,
      num_classes: 10,
      freeze_backbone: false,
    },
    uiSchema: {
      family: {
        type: 'enum',
        options: ['resnet18', 'resnet50', 'efficientnet', 'vit', 'xgboost', 'random_forest', 'mlp', 'bert', 'roberta', 'lstm', 'custom'],
        label: 'Model',
      },
      pretrained: { type: 'boolean', label: 'Pretrained' },
      num_classes: { type: 'number', min: 1, max: 100000, step: 1, label: 'Num Classes' },
      freeze_backbone: { type: 'boolean', label: 'Freeze Backbone' },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.loss',
    label: 'Loss Function',
    category: 'training-config',
    accepts: ['model'],
    produces: ['loss'],
    inputs: [{ name: 'model', datatype: 'model', shape: [], optional: true }],
    outputs: [{ name: 'loss', datatype: 'loss', shape: [] }],
    defaultConfig: {
      name: 'cross_entropy',
      reduction: 'mean',
      class_weights: 'auto',
      label_smoothing: 0.1,
    },
    uiSchema: {
      name: { type: 'enum', options: ['cross_entropy', 'focal_loss', 'dice_loss', 'mse', 'huber', 'triplet_loss', 'contrastive_loss', 'custom'] },
      reduction: { type: 'enum', options: ['mean', 'sum', 'none'] },
      class_weights: { type: 'string', label: 'Class Weights' },
      label_smoothing: { type: 'number', min: 0, max: 1, step: 0.01 },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.training',
    label: 'Training',
    category: 'training-execution',
    accepts: ['model', 'loss', 'dataloader', ...DATA_INPUTS],
    produces: ['trained_model', 'metrics', 'logs'],
    inputs: [
      { name: 'model', datatype: 'model', shape: [], optional: false },
      { name: 'loader', datatype: 'dataloader', shape: [], optional: false },
      { name: 'loss', datatype: 'loss', shape: [], optional: true },
      { name: 'config', datatype: 'dict', shape: [], optional: true },
    ],
    outputs: [
      { name: 'trained_model', datatype: 'model', shape: [] },
      { name: 'metrics', datatype: 'dict', shape: [] },
      { name: 'logs', datatype: 'dict', shape: [] },
      { name: 'checkpoints', datatype: 'dict', shape: [] },
    ],
    defaultConfig: {
      optimizer: 'adamw',
      learning_rate: 0.001,
      weight_decay: 0.0001,
      scheduler: 'cosine',
      epochs: 50,
      gradient_clipping: 1,
      mixed_precision: true,
      checkpoint_frequency: 1,
      early_stopping: true,
      monitor_metric: 'val_loss',
      gradient_accumulation: 1,
      logging_backend: 'tensorboard',
    },
    uiSchema: {
      optimizer: { type: 'enum', options: ['adam', 'sgd', 'adamw'] },
      learning_rate: { type: 'number', min: 0, max: 10, step: 0.0001 },
      weight_decay: { type: 'number', min: 0, max: 1, step: 0.0001 },
      scheduler: { type: 'enum', options: ['cosine', 'step', 'linear', 'none'] },
      epochs: { type: 'number', min: 1, max: 10000, step: 1 },
      gradient_clipping: { type: 'number', min: 0, max: 100, step: 0.1 },
      mixed_precision: { type: 'boolean' },
      checkpoint_frequency: { type: 'number', min: 1, max: 1000, step: 1 },
      early_stopping: { type: 'boolean' },
      monitor_metric: { type: 'string' },
      gradient_accumulation: { type: 'number', min: 1, max: 512, step: 1 },
      logging_backend: { type: 'enum', options: ['tensorboard', 'mlflow', 'wandb', 'none'] },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.evaluate',
    label: 'Evaluate',
    category: 'evaluation',
    accepts: [...MODEL_INPUTS, 'dataloader', ...DATA_INPUTS],
    produces: ['metrics', 'predictions', 'confusion_matrix'],
    inputs: [
      { name: 'trained_model', datatype: 'model', shape: [], optional: false },
      { name: 'test_loader', datatype: 'dataloader', shape: [], optional: true },
    ],
    outputs: [
      { name: 'metrics', datatype: 'dict', shape: [] },
      { name: 'predictions', datatype: 'dict', shape: [] },
      { name: 'confusion_matrix', datatype: 'dict', shape: [] },
    ],
    defaultConfig: {
      metrics: ['accuracy', 'f1', 'auc'],
      threshold: 0.5,
    },
    uiSchema: {
      metrics: { type: 'multiselect', options: ['accuracy', 'precision', 'recall', 'f1', 'auc'] },
      threshold: { type: 'number', min: 0, max: 1, step: 0.01 },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.predict',
    label: 'Predict',
    category: 'inference',
    accepts: [...MODEL_INPUTS, ...DATA_INPUTS, 'dataloader'],
    produces: ['predictions', 'confidence_scores'],
    inputs: [
      { name: 'trained_model', datatype: 'model', shape: [], optional: false },
      { name: 'new_data', datatype: 'tensor', shape: [], optional: true },
    ],
    outputs: [
      { name: 'predictions', datatype: 'dict', shape: [] },
      { name: 'confidence_scores', datatype: 'dict', shape: [] },
    ],
    defaultConfig: {
      batch_size: 32,
      return_probabilities: true,
      threshold: 0.5,
    },
    uiSchema: {
      batch_size: { type: 'number', min: 1, max: 4096, step: 1 },
      return_probabilities: { type: 'boolean' },
      threshold: { type: 'number', min: 0, max: 1, step: 0.01 },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.metrics',
    label: 'Metrics',
    category: 'evaluation',
    accepts: [...PREDICTION_INPUTS, 'dict'],
    produces: ['metrics'],
    inputs: [
      { name: 'predictions', datatype: 'dict', shape: [], optional: false },
      { name: 'ground_truth', datatype: 'dict', shape: [], optional: true },
    ],
    outputs: [{ name: 'metric_dict', datatype: 'dict', shape: [] }],
    defaultConfig: {
      metric_names: ['accuracy', 'precision', 'recall', 'f1', 'auc'],
      average_type: 'binary',
      threshold: 0.5,
    },
    uiSchema: {
      metric_names: { type: 'multiselect', options: ['accuracy', 'precision', 'recall', 'f1', 'auc'] },
      average_type: { type: 'enum', options: ['binary', 'micro', 'macro', 'weighted'] },
      threshold: { type: 'number', min: 0, max: 1, step: 0.01 },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.export',
    label: 'Export',
    category: 'deployment',
    accepts: [...MODEL_INPUTS, 'metrics', 'predictions'],
    produces: ['model_path', 'artifacts'],
    inputs: [
      { name: 'trained_model', datatype: 'model', shape: [], optional: false },
      { name: 'metrics', datatype: 'dict', shape: [], optional: true },
      { name: 'predictions', datatype: 'dict', shape: [], optional: true },
    ],
    outputs: [
      { name: 'model_path', datatype: 'string', shape: [] },
      { name: 'artifacts', datatype: 'dict', shape: [] },
    ],
    defaultConfig: {
      format: 'onnx',
      path: 'artifacts/model',
      include_predictions: true,
      include_metrics: true,
    },
    uiSchema: {
      format: { type: 'enum', options: ['onnx', 'pytorch', 'tensorflow'] },
      path: { type: 'string' },
      include_predictions: { type: 'boolean' },
      include_metrics: { type: 'boolean' },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.validate',
    label: 'Validate Data',
    category: 'data-control',
    accepts: DATA_INPUTS,
    produces: ['validation_report', ...DATA_INPUTS],
    inputs: [{ name: 'dataset', datatype: 'tensor', shape: [], optional: false }],
    outputs: [
      { name: 'validation_report', datatype: 'dict', shape: [] },
      { name: 'cleaned_data', datatype: 'tensor', shape: [] },
    ],
    defaultConfig: {
      rules: [],
      missing_threshold: 0.2,
      outlier_detection: 'none',
    },
    uiSchema: {
      rules: { type: 'array' },
      missing_threshold: { type: 'number', min: 0, max: 1, step: 0.01 },
      outlier_detection: { type: 'enum', options: ['none', 'iqr', 'zscore'] },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.hyperparameter_tune',
    label: 'Hyperparameter Tune',
    category: 'training-execution',
    accepts: [...MODEL_INPUTS, 'dataloader', ...DATA_INPUTS],
    produces: ['best_model', 'best_params', 'tuning_history'],
    inputs: [
      { name: 'model', datatype: 'model', shape: [], optional: false },
      { name: 'train_loader', datatype: 'dataloader', shape: [], optional: true },
      { name: 'val_loader', datatype: 'dataloader', shape: [], optional: true },
    ],
    outputs: [
      { name: 'best_model', datatype: 'model', shape: [] },
      { name: 'best_params', datatype: 'dict', shape: [] },
      { name: 'tuning_history', datatype: 'dict', shape: [] },
    ],
    defaultConfig: {
      param_grid: {
        learning_rate: [0.001, 0.0005],
        weight_decay: [0.0, 0.0001],
      },
      search_method: 'grid',
      max_trials: 10,
      objective: 'val_accuracy',
    },
    uiSchema: {
      param_grid: { type: 'json' },
      search_method: { type: 'enum', options: ['grid', 'random', 'bayes'] },
      max_trials: { type: 'number', min: 1, max: 1000, step: 1 },
      objective: { type: 'string' },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.ensemble',
    label: 'Ensemble',
    category: 'modeling',
    accepts: [...MODEL_INPUTS],
    produces: ['ensemble_model', 'weights'],
    inputs: [{ name: 'models', datatype: 'model', shape: [], optional: false }],
    outputs: [
      { name: 'ensemble_model', datatype: 'model', shape: [] },
      { name: 'weights', datatype: 'dict', shape: [] },
    ],
    defaultConfig: {
      method: 'voting',
      weights: [],
    },
    uiSchema: {
      method: { type: 'enum', options: ['voting', 'stacking', 'blending'] },
      weights: { type: 'array' },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.feature_engineer',
    label: 'Feature Engineer',
    category: 'preprocessing',
    accepts: DATA_INPUTS,
    produces: DATA_INPUTS,
    inputs: [{ name: 'dataset', datatype: 'tensor', shape: [], optional: false }],
    outputs: [{ name: 'engineered_data', datatype: 'tensor', shape: [] }],
    defaultConfig: {
      strategy: 'auto',
      operations: [],
    },
    uiSchema: {
      strategy: { type: 'enum', options: ['auto', 'manual'] },
      operations: { type: 'array' },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.model_compare',
    label: 'Model Compare',
    category: 'evaluation',
    accepts: [...MODEL_INPUTS, 'metrics'],
    produces: ['comparison_report', 'best_model'],
    inputs: [
      { name: 'models', datatype: 'model', shape: [], optional: false },
      { name: 'metrics', datatype: 'dict', shape: [], optional: true },
    ],
    outputs: [
      { name: 'comparison_report', datatype: 'dict', shape: [] },
      { name: 'best_model', datatype: 'model', shape: [] },
    ],
    defaultConfig: {
      primary_metric: 'accuracy',
      higher_is_better: true,
    },
    uiSchema: {
      primary_metric: { type: 'string' },
      higher_is_better: { type: 'boolean' },
    },
  }),
  createLifecycleDef({
    type: 'lifecycle.serve',
    label: 'Serve',
    category: 'deployment',
    accepts: [...MODEL_INPUTS, 'ensemble_model'],
    produces: ['endpoint', 'serve_artifacts'],
    inputs: [{ name: 'trained_model', datatype: 'model', shape: [], optional: false }],
    outputs: [
      { name: 'endpoint', datatype: 'string', shape: [] },
      { name: 'serve_artifacts', datatype: 'dict', shape: [] },
    ],
    defaultConfig: {
      protocol: 'http',
      port: 8000,
      route: '/predict',
      replicas: 1,
    },
    uiSchema: {
      protocol: { type: 'enum', options: ['http', 'grpc'] },
      port: { type: 'number', min: 1, max: 65535, step: 1 },
      route: { type: 'string' },
      replicas: { type: 'number', min: 1, max: 128, step: 1 },
    },
  }),
];
