function pyString(v) {
  const s = String(v ?? '');
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function pyValue(v) {
  if (v === null || v === undefined) return 'None';
  if (typeof v === 'boolean') return v ? 'True' : 'False';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'None';
  if (typeof v === 'string') return pyString(v);
  if (Array.isArray(v)) return `[${v.map((it) => pyValue(it)).join(', ')}]`;
  if (typeof v === 'object') {
    const entries = Object.entries(v).map(([k, val]) => `${pyString(k)}: ${pyValue(val)}`);
    return `{${entries.join(', ')}}`;
  }
  return pyString(String(v));
}

function imageTemplate(config) {
  return [
    '# Auto-generated template for dataset.image',
    'import os',
    'from pathlib import Path',
    '',
    `config = ${pyValue(config)}`,
    `path = ${pyValue(config.path || './data/images')}`,
    '',
    'def resolve_client_uri(uri_path):',
    '    """Map client://upload_* URIs to actual filesystem paths."""',
    '    if isinstance(uri_path, str) and uri_path.startswith("client://"):',
    '        parts = uri_path.replace("client://", "").split("_", 1)',
    '        if len(parts) == 2 and parts[0] == "upload":',
    '            timestamp_hash = parts[1]',
    '            candidates = [',
    '                Path("data/uploads") / timestamp_hash,',
    '                Path("./uploads") / timestamp_hash,',
    '                Path("tmp/uploads") / timestamp_hash,',
    '            ]',
    '            for cand in candidates:',
    '                if cand.exists() and cand.is_dir():',
    '                    return cand',
    '            upload_base = os.getenv("UPLOAD_BASE_PATH")',
    '            if upload_base:',
    '                resolved = Path(upload_base) / timestamp_hash',
    '                if resolved.exists():',
    '                    return resolved',
    '            raise ValueError(f"client:// URI resolved to no path: {uri_path}")',
    '    return Path(uri_path) if uri_path else None',
    '',
    'dataset_root = resolve_client_uri(path)',
    'if dataset_root is None or not dataset_root.exists():',
    '    raise ValueError(f"Invalid image dataset root path: {path}")',
    '',
    'image_extensions = {".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp", ".tiff"}',
    'image_files = []',
    'for img_path in sorted(dataset_root.rglob("*")):',
    '    if img_path.is_file() and img_path.suffix.lower() in image_extensions:',
    '        image_files.append({',
    '            "path": str(img_path.relative_to(dataset_root)),',
    '            "full_path": str(img_path.resolve()),',
    '            "size": img_path.stat().st_size,',
    '            "ext": img_path.suffix.lower(),',
    '        })',
    '',
    'print(f"Image dataset loaded: {len(image_files)} images found")',
    'for img in image_files[:5]:',
    '    print(f"  - {img[\'path\']} ({img[\'size\'] / 1024:.1f} KB)")',
    'if len(image_files) > 5:',
    '    print(f"  ... and {len(image_files) - 5} more")',
    '',
    'dataset_info = {',
    '    "type": "image",',
    '    "count": len(image_files),',
    '    "root": str(dataset_root),',
    '    "files": image_files[:50],  # Return first 50 for preview',
    '}',
    'print("Dataset ready:", dataset_info)',
  ].join('\n');
}

function csvTemplate(config) {
  const features = Array.isArray(config.features) && config.features.length > 0
    ? config.features
    : (Array.isArray(config.feature_columns) ? config.feature_columns : []);

  const relations = Array.isArray(config.relations) ? config.relations : [];
  const files = Array.isArray(config.files) ? config.files : [];
  const normalizedConfig = {
    source_mode: config.source_mode || 'folder',
    path: config.path || './data',
    files,
    primary: config.primary || '',
    relations,
    target_column: config.target_column || '',
    features,
    delimiter: config.delimiter || ',',
    header: config.header !== false,
    missing: config.missing || { strategy: config.handle_missing || 'drop' },
  };

  return [
    '# Auto-generated template for dataset.csv',
    'import pandas as pd',
    'import os',
    'from pathlib import Path',
    '',
    `config = ${pyValue(normalizedConfig)}`,
    `path = ${pyValue(normalizedConfig.path)}`,
    `delimiter = ${pyValue(normalizedConfig.delimiter)}`,
    `has_header = ${pyValue(normalizedConfig.header)}`,
    `selected_files = ${pyValue(normalizedConfig.files)}`,
    `primary = ${pyValue(normalizedConfig.primary)}`,
    `relations = ${pyValue(relations)}`,
    `target_column = ${pyValue(normalizedConfig.target_column)}`,
    `features = ${pyValue(features)}`,
    `missing = ${pyValue(normalizedConfig.missing)}`,
    `chunk_size = ${pyValue(config.chunk_size || null)}  # For large files; None = load all`,
    '',
    'def resolve_client_uri(uri_path):',
    '    """Map client://upload_* URIs to actual filesystem paths."""',
    '    if isinstance(uri_path, str) and uri_path.startswith("client://"):',
    '        # client://upload_<timestamp>_<hash> → data/uploads/<timestamp>-<hash>/',
    '        parts = uri_path.replace("client://", "").split("_", 1)',
    '        if len(parts) == 2 and parts[0] == "upload":',
    '            timestamp_hash = parts[1]',
    '            # Try common upload paths',
    '            candidates = [',
    '                Path("data/uploads") / timestamp_hash,',
    '                Path("./uploads") / timestamp_hash,',
    '                Path("tmp/uploads") / timestamp_hash,',
    '            ]',
    '            for cand in candidates:',
    '                if cand.exists() and cand.is_dir():',
    '                    return cand',
    '            # If not found locally, try env override',
    '            upload_base = os.getenv("UPLOAD_BASE_PATH")',
    '            if upload_base:',
    '                resolved = Path(upload_base) / timestamp_hash',
    '                if resolved.exists():',
    '                    return resolved',
    '            raise ValueError(f"client:// URI resolved to no path: {uri_path}")',
    '    return Path(uri_path) if uri_path else None',
    '',
    'dataset_root = resolve_client_uri(path)',
    'if dataset_root is None:',
    '    raise ValueError(f"Invalid dataset root path: {path}")',
    '',
    'def resolve_existing_path(raw_path):',
    '    p = Path(raw_path)',
    '    candidates = []',
    '    if p.is_absolute():',
    '        candidates.append(p)',
    '    else:',
    '        if dataset_root.exists() and dataset_root.is_dir():',
    '            candidates.append(dataset_root / p)',
    '        candidates.append(p)',
    '        candidates.append(Path.cwd() / p)',
    '    for cand in candidates:',
    '        if cand.exists():',
    '            return cand.resolve()',
    '    return None',
    '',
    'csv_entries = []  # [(table_name, file_path)]',
    'if isinstance(selected_files, dict) and selected_files:',
    '    for table_name, raw_file in selected_files.items():',
    '        resolved = resolve_existing_path(raw_file)',
    "        if not resolved or resolved.suffix.lower() != '.csv':",
    '            print(f"Warning: file for table {table_name!r} not found or not CSV: {raw_file}")',
    '            continue',
    '        csv_entries.append((str(table_name), resolved))',
    'elif isinstance(selected_files, list) and selected_files:',
    '    for raw_file in selected_files:',
    '        resolved = resolve_existing_path(raw_file)',
    "        if not resolved or resolved.suffix.lower() != '.csv':",
    '            print(f"Warning: configured CSV file not found or not CSV: {raw_file}")',
    '            continue',
    '        csv_entries.append((resolved.stem, resolved))',
    'else:',
    '    if dataset_root.exists() and dataset_root.is_file() and dataset_root.suffix.lower() == ".csv":',
    '        csv_entries = [(dataset_root.stem, dataset_root.resolve())]',
    '    elif dataset_root.exists() and dataset_root.is_dir():',
    '        csv_entries = [(p.stem, p.resolve()) for p in sorted(dataset_root.rglob("*.csv"))]',
    '',
    'if not csv_entries:',
    '    raise FileNotFoundError(f"No CSV files resolved from path/files config: {path}, files={selected_files}")',
    '',
    '# Infer datetime columns from feature list (common patterns)',
    'datetime_features = [f for f in features if any(dt in f.lower() for dt in ["date", "time", "day", "month", "year"])]',
    'parse_dates = datetime_features if datetime_features else []',
    '',
    'tables = {}',
    'for table_name, file_path in csv_entries:',
    '    read_kwargs = {',
    '        "sep": delimiter,',
    '        "header": 0 if has_header else None,',
    '        "parse_dates": parse_dates,',
    '        "dayfirst": True,  # Handle dd-mm-yyyy format',
    '    }',
    '    if chunk_size:',
    '        # For large files: process in chunks',
    '        tables[table_name] = pd.concat([chunk for chunk in pd.read_csv(file_path, chunksize=chunk_size, **read_kwargs)])',
    '    else:',
    '        tables[table_name] = pd.read_csv(file_path, **read_kwargs)',
    '',
    'print("Loaded tables:", list(tables.keys()))',
    '',
    'if not primary or primary not in tables:',
    '    fallback = next(iter(tables.keys()))',
    '    print(f"Warning: primary table {primary!r} not found; using {fallback!r}.")',
    '    primary = fallback',
    'df = tables[primary]',
    '',
    'for rel in relations:',
    '    left = rel.get("left") or primary',
    '    right = rel.get("right")',
    '    on = rel.get("on")',
    '    how = rel.get("type", "left")',
    '    if left != primary:',
    '        print(f"Warning: relation left={left!r} is not the primary table {primary!r}; skipping")',
    '        continue',
    '    if not right or right not in tables or not on:',
    '        continue',
    '    if on not in df.columns or on not in tables[right].columns:',
    '        print(f"Warning: join key {on!r} missing in table {left!r} or {right!r}; skipping")',
    '        continue',
    '    df = df.merge(tables[right], on=on, how=how)',
    '',
    'missing_strategy = (missing or {}).get("strategy", "drop")',
    'if missing_strategy in {"drop", "drop_rows"}:',
    '    before = len(df)',
    '    df = df.dropna()',
    '    print(f"Dropped {before - len(df)} rows with nulls (strategy={missing_strategy})")',
    'elif missing_strategy == "mean":',
    '    nulls_before = int(df.isna().sum().sum())',
    '    df = df.fillna(df.mean(numeric_only=True))',
    '    nulls_after = int(df.isna().sum().sum())',
    '    print(f"Filled {nulls_before - nulls_after} nulls with numeric means")',
    '',
    '# Explicitly exclude leak-prone columns (cost/profit derivable from target)',
    'exclude_cols = [c for c in ["cost", "profit"] if c in df.columns]',
    'if exclude_cols:',
    '    print(f"Dropped columns (potential target leakage): {exclude_cols}")',
    '    df = df.drop(columns=exclude_cols)',
    '',
    'if features:',
    '    selected = [c for c in features if c in df.columns]',
    '    # Re-apply exclusions after feature selection',
    '    selected = [c for c in selected if c not in exclude_cols]',
    '    if target_column and target_column in df.columns and target_column not in selected:',
    '        selected.append(target_column)',
    '    if selected:',
    '        df = df[selected]',
    'else:',
    '    print("Warning: features is empty; model-ready feature matrix is not explicitly constrained.")',
    '',
    "if target_column and target_column in df.columns:",
    '    y = df[target_column]',
    '    X = df.drop(columns=[target_column])',
    'else:',
    '    y = None',
    '    X = df',
    '',
    'numerical = list(X.select_dtypes(include="number").columns)',
    'categorical = list(X.select_dtypes(include="object").columns)',
    'datetime_cols = list(X.select_dtypes(include="datetime64").columns)',
    '',
    'dataset_info = {',
    '    "rows": len(df),',
    '    "columns": len(df.columns),',
    '    "features": list(X.columns),',
    '    "target": target_column or None,',
    '    "primary": primary,',
    '    "tables": list(tables.keys()),',
    '    "numerical": numerical,',
    '    "categorical": categorical,',
    '    "datetime": datetime_cols,',
    '}',
    '',
    'print("Dataset ready:", dataset_info)',
  ].join('\n');
}

function textTemplate(config) {
  return [
    '# Auto-generated template for dataset.text',
    'import json',
    'import os',
    'from pathlib import Path',
    '',
    `config = ${pyValue(config)}`,
    `path = ${pyValue(config.path || './data/corpus.txt')}`,
    `file_format = ${pyValue(config.file_format || 'txt')}`,
    `text_column = ${pyValue(config.text_column || 'text')}`,
    `label_column = ${pyValue(config.label_column || 'label')}`,
    '',
    'def resolve_client_uri(uri_path):',
    '    """Map client://upload_* URIs to actual filesystem paths."""',
    '    if isinstance(uri_path, str) and uri_path.startswith("client://"):',
    '        parts = uri_path.replace("client://", "").split("_", 1)',
    '        if len(parts) == 2 and parts[0] == "upload":',
    '            timestamp_hash = parts[1]',
    '            candidates = [',
    '                Path("data/uploads") / timestamp_hash,',
    '                Path("./uploads") / timestamp_hash,',
    '                Path("tmp/uploads") / timestamp_hash,',
    '            ]',
    '            for cand in candidates:',
    '                if cand.exists() and cand.is_dir():',
    '                    return cand',
    '            upload_base = os.getenv("UPLOAD_BASE_PATH")',
    '            if upload_base:',
    '                resolved = Path(upload_base) / timestamp_hash',
    '                if resolved.exists():',
    '                    return resolved',
    '            raise ValueError(f"client:// URI resolved to no path: {uri_path}")',
    '    return Path(uri_path) if uri_path else None',
    '',
    'dataset_root = resolve_client_uri(path)',
    'if dataset_root is None or not dataset_root.exists():',
    '    dataset_root = Path(path)',
    '',
    'records = []',
    'text_files = []',
    '',
    'try:',
    "    if file_format == 'txt':",
    "        if dataset_root.is_file():",
    "            text_files = [dataset_root]",
    "        else:",
    "            text_extensions = {'.txt', '.md', '.text'}",
    "            text_files = [f for f in dataset_root.rglob('*') if f.suffix.lower() in text_extensions]",
    "    elif file_format == 'jsonl':",
    "        if dataset_root.is_file():",
    "            text_files = [dataset_root]",
    "        else:",
    "            text_files = [f for f in dataset_root.rglob('*.jsonl')]",
    "    else:  # csv",
    "        if dataset_root.is_file():",
    "            text_files = [dataset_root]",
    "        else:",
    "            text_files = [f for f in dataset_root.rglob('*.csv')]",
    "    ",
    "    for text_file in sorted(text_files):",
    "        try:",
    "            content = text_file.read_text(encoding='utf-8')",
    "            if file_format == 'txt':",
    "                for line in content.splitlines():",
    "                    line = line.strip()",
    "                    if line:",
    "                        records.append({'text': line, 'source': text_file.name})",
    "            elif file_format == 'jsonl':",
    "                for line in content.splitlines():",
    "                    line = line.strip()",
    "                    if line:",
    "                        try:",
    "                            obj = json.loads(line)",
    "                            records.append({'text': obj.get(text_column, ''), 'label': obj.get(label_column), 'source': text_file.name})",
    "                        except json.JSONDecodeError:",
    "                            pass",
    "            else:  # csv",
    "                import csv",
    "                with text_file.open('r', encoding='utf-8', newline='') as f:",
    "                    reader = csv.DictReader(f)",
    "                    for row in reader:",
    "                        records.append({'text': row.get(text_column, ''), 'label': row.get(label_column), 'source': text_file.name})",
    "        except Exception as e:",
    "            print(f\"Warning: Failed to read {text_file.name}: {e}\")",
    "            continue",
    '',
    'except Exception as e:',
    '    print(f"Error reading text dataset: {e}")',
    '',
    'print(f"Text records loaded: {len(records)} records, {len(text_files)} files")',
    'for f in text_files[:3]:',
    '    print(f"  - {f.name}")',
    '',
    'dataset_info = {',
    '    "type": "text",',
    '    "count": len(records),',
    '    "file_count": len(text_files),',
    '    "records": records[:50],  # First 50 for preview',
    '}',
    'print("Dataset ready:", dataset_info)',
  ].join('\n');
}

function jsonTemplate(config) {
  return [
    '# Auto-generated template for dataset.json',
    'import json',
    'import os',
    'import pandas as pd',
    'from pathlib import Path',
    '',
    `config = ${pyValue(config)}`,
    `path = ${pyValue(config.path || './data/data.json')}`,
    `file_format = ${pyValue(config.file_format || 'json')}`,
    `data_key = ${pyValue(config.data_key || '')}`,
    '',
    'def resolve_client_uri(uri_path):',
    '    """Map client://upload_* URIs to actual filesystem paths."""',
    '    if isinstance(uri_path, str) and uri_path.startswith("client://"):',
    '        parts = uri_path.replace("client://", "").split("_", 1)',
    '        if len(parts) == 2 and parts[0] == "upload":',
    '            timestamp_hash = parts[1]',
    '            candidates = [',
    '                Path("data/uploads") / timestamp_hash,',
    '                Path("./uploads") / timestamp_hash,',
    '                Path("tmp/uploads") / timestamp_hash,',
    '            ]',
    '            for cand in candidates:',
    '                if cand.exists() and cand.is_dir():',
    '                    return cand',
    '            upload_base = os.getenv("UPLOAD_BASE_PATH")',
    '            if upload_base:',
    '                resolved = Path(upload_base) / timestamp_hash',
    '                if resolved.exists():',
    '                    return resolved',
    '            raise ValueError(f"client:// URI resolved to no path: {uri_path}")',
    '    return Path(uri_path) if uri_path else None',
    '',
    'dataset_root = resolve_client_uri(path)',
    'if dataset_root is None:',
    '    dataset_root = Path(path)',
    '',
    'def get_by_path(obj, dot_path):',
    '    """Extract nested value by dot notation (e.g. \'data.records\')."""',
    '    if not dot_path:',
    '        return obj',
    '    cur = obj',
    "    for part in dot_path.split('.'):",
    '        if isinstance(cur, dict):',
    '            cur = cur.get(part)',
    '        else:',
    '            return None',
    '    return cur',
    '',
    'records = []',
    'json_files = []',
    '',
    'try:',
    "    if file_format == 'jsonl':",
    "        if dataset_root.is_file():",
    "            json_files = [dataset_root]",
    "        else:",
    "            json_files = [f for f in dataset_root.rglob('*.jsonl')]",
    "    else:",
    "        if dataset_root.is_file():",
    "            json_files = [dataset_root]",
    "        else:",
    "            json_files = [f for f in dataset_root.rglob('*.json')]",
    "    ",
    "    for json_file in sorted(json_files):",
    "        try:",
    "            content = json_file.read_text(encoding='utf-8')",
    "            if file_format == 'jsonl':",
    "                for line in content.splitlines():",
    "                    line = line.strip()",
    "                    if line:",
    "                        try:",
    "                            obj = json.loads(line)",
    "                            records.append(obj)",
    "                        except json.JSONDecodeError:",
    "                            pass",
    "            else:",
    "                payload = json.loads(content)",
    "                if data_key:",
    "                    extracted = get_by_path(payload, data_key)",
    "                else:",
    "                    extracted = payload",
    "                ",
    "                if isinstance(extracted, list):",
    "                    records.extend(extracted)",
    "                elif isinstance(extracted, dict):",
    "                    records.append(extracted)",
    "        except Exception as e:",
    "            print(f\"Warning: Failed to read {json_file.name}: {e}\")",
    "            continue",
    '',
    'except Exception as e:',
    '    print(f"Error reading JSON dataset: {e}")',
    '',
    '# Try to convert to DataFrame for better preview',
    'try:',
    '    df = pd.DataFrame(records)',
    '    print(f"JSON records loaded: {len(df)} rows, {len(df.columns)} columns")',
    'except:',
    '    df = None',
    '    print(f"JSON records loaded: {len(records)} records (non-tabular)")',
    '',
    'dataset_info = {',
    '    "type": "json",',
    '    "count": len(records),',
    '    "file_count": len(json_files),',
    '    "records": records[:50],  # First 50 for preview',
    '    "is_tabular": df is not None,',
    '    "columns": list(df.columns) if df is not None else [],',
    '}',
    'print("Dataset ready:", dataset_info)',
  ].join('\n');
}

function databaseTemplate(config) {
  return [
    '# Auto-generated template for dataset.database',
    '# NOTE: This is a template scaffold. Executor integration will provide connectors.',
    '',
    `config = ${pyValue(config)}`,
    `db_type = ${pyValue(config.db_type || 'postgresql')}`,
    `host = ${pyValue(config.host || 'localhost')}`,
    `database = ${pyValue(config.database || '')}`,
    `table = ${pyValue(config.table || '')}`,
    `query = ${pyValue(config.query || '')}`,
    '',
    'if query:',
    '    sql = query',
    'elif table:',
    '    sql = f"SELECT * FROM {table}"',
    'else:',
    '    sql = None',
    '',
    'print(f"DB type: {db_type}, host: {host}, database: {database}")',
    'print(f"Query: {sql}")',
  ].join('\n');
}

function apiTemplate(config) {
  return [
    '# Auto-generated template for dataset.api',
    'import requests',
    '',
    `config = ${pyValue(config)}`,
    `url = ${pyValue(config.url || '')}`,
    `method = ${pyValue(config.method || 'GET')}`,
    `auth_type = ${pyValue(config.auth_type || 'none')}`,
    `token = ${pyValue(config.auth_token || '')}`,
    '',
    'headers = {}',
    "if auth_type == 'bearer' and token:",
    '    headers["Authorization"] = f"Bearer {token}"',
    '',
    'resp = requests.request(method=method, url=url, headers=headers, timeout=30)',
    'resp.raise_for_status()',
    'payload = resp.json()',
    `data_path = ${pyValue(config.data_path || 'data')}`,
    '# TODO: extract nested payload by data_path in executor runtime',
    'print("Fetched payload keys:", list(payload.keys()) if isinstance(payload, dict) else type(payload))',
  ].join('\n');
}

export function generateDatasetPythonCode(nodeType, config = {}) {
  switch (nodeType) {
    case 'dataset.image':
      return imageTemplate(config);
    case 'dataset.csv':
      return csvTemplate(config);
    case 'dataset.text':
      return textTemplate(config);
    case 'dataset.json':
      return jsonTemplate(config);
    case 'dataset.database':
      return databaseTemplate(config);
    case 'dataset.api':
      return apiTemplate(config);
    default:
      return [
        '# Auto-generated dataset template',
        `# Unknown node type: ${nodeType}`,
        `config = ${pyValue(config)}`,
      ].join('\n');
  }
}
